### ISSUE TITLE
Timeout error 

### ISSUE THREAD

**Issue by chetan1001** [Azure-Samples/azure-cosmos-db-graph-java-getting-started#18]
I am getting the following exception when I run through this program. Any advise? THanks. 

Submitting this Gremlin query: g.V()
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timed out while waiting for an available host - check the client configuration and connectivity to the server if this message persists
	at org.apache.tinkerpop.gremlin.driver.Client.submit(Client.java:218)
	at org.apache.tinkerpop.gremlin.driver.Client.submit(Client.java:187)
	at GetStarted.Program.main(Program.java:66)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timed out while waiting for an available host - check the client configuration and connectivity to the server if this message persists
	at org.apache.tinkerpop.gremlin.driver.Client.submitAsync(Client.java:339)
	at org.apache.tinkerpop.gremlin.driver.Client.submitAsync(Client.java:317)
	at org.apache.tinkerpop.gremlin.driver.Client.submit(Client.java:216)
	... 2 more
Caused by: java.util.concurrent.TimeoutException: Timed out while waiting for an available host - check the client configuration and connectivity to the server if this message persists
	at org.apache.tinkerpop.gremlin.driver.Client$ClusteredClient.chooseConnection(Client.java:463)
	at org.apache.tinkerpop.gremlin.driver.Client.submitAsync(Client.java:334)
	... 4 more

**Comment by olivertowers** [comment]
Does this happen for any gremlin request issued from the client?
If it is then this might be a connection misconfiguration:

- Double check your `hosts` endpoint is of format `<account-name>.gremlin.cosmos.azure.com` and port is `443`
- Do you have any firewalls configured on the account and is your machine IP configured correctly?
- Make sure you have imported the required root certs https://learn.microsoft.com/en-us/azure/security/fundamentals/azure-ca-details

If this is still happening try running gremlin queries from the [Azure Cosmos DB portal data explorer](https://learn.microsoft.com/en-us/azure/cosmos-db/data-explorer) on the same machine. This should determine if your machine has the ability to connect to Cosmos DB Gremlin via the browser.

**Comment by olivertowers** [comment]
No additional information provided. Closing the issue.
